---
# enable the nxapi
# configure the layer 3 interface ip address

- name: configure the interface
  hosts: nxos
  gather_facts: no

  tasks:
    - name: set the ipv4 address
      nxos_l3_interface:
        aggregate:
          - { name: Ethernet1/2, ipv4: 192.168.1.2/24 }
          - { name: Ethernet1/3, ipv4: 192.168.2.3/24 }
