---
# enable the nxapi
# configure the layer 3 interface ip address

- name: configure the interface
  hosts: nxos
  gather_facts: no

  tasks:
    - name : set the interface to layer3 and name description
      nxos_interface:
        aggregate:
          - { name: Ethernet1/2, mtu: 1400, description: "to e1/2 {{inventory_hostname}}"}
          - { name: Ethernet1/3, mtu: 1400, description: "to e1/3 {{inventory_hostname}}"}
        speed: 100
        mode: layer3

    - name: set the ipv4 address
      nxos_l3_interface:
        aggregate:
          - { name: Ethernet1/2, ipv4: 192.168.1.2/24 }
          - { name: Ethernet1/3, ipv4: 192.168.1.3/24 }